# Generated by Django 3.2 on 2021-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
