# Generated by Django 3.2 on 2021-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_orderupdate_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=30000),
        ),
    ]
